name: Product Service CI
on:
  push:
    branches:
      - main
    paths:
      - "product-service/**"
  pull_request:
    branches:
      - main
    paths:
      - "product-service/**"
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker Image Tag (example: 1.0.0)"
        required: true
        default: "1.0.0"
env:
  AWS_REGION: ap-south-1
  IMAGE_TAG: ${{ github.sha }}
  SERVICE_NAME: product-service
jobs:
  product-service-build:
    name: Product Service Build Test Docker Push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Validate
        working-directory: product-service
        run: mvn validate
      - name: Unit Test
        working-directory: product-service
        run: mvn test
      - name: Build Package
        working-directory: product-service
        run: mvn clean package -DskipTests
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Assume Deployment Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::519765643705:role/github-actions-ecr-role
          role-chaining: true
          aws-region: ap-south-1
          role-skip-session-tagging: true
      - name: Login ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Docker Build
        run: |
          docker build -t ${SERVICE_NAME}:${IMAGE_TAG} ./product-service
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: ${{ secrets.PRODUCT_ECR }}:${{ github.sha }}
          severity: HIGH,CRITICAL
          exit-code: 0
      - name: Docker Image Tag
        run: |
          docker tag ${SERVICE_NAME}:${IMAGE_TAG} ${{ secrets.PRODUCT_ECR }}:${IMAGE_TAG}
      - name: Push Image
        run: |
          docker push ${{ secrets.PRODUCT_ECR }}:${IMAGE_TAG}
