name: User Service CI
on:
  push:
    branches:
      - main
    paths:
      - "user-service/**"
  pull_request:
    branches:
      - main
    paths:
      - "user-service/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - uat
          - prod
env:
  AWS_REGION: ap-south-1
  IMAGE_TAG: ${{ github.sha }}
jobs:
  user-service-build:
    name: User Service Build Test Docker Push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Validate
        working-directory: user-service
        run: mvn validate
      - name: Dependency Scan
        working-directory: user-service
        run: mvn org.owasp:dependency-check-maven:check
      - name: Unit Test
        working-directory: user-service
        run: mvn test
      - name: Build Package
        working-directory: user-service
        run: mvn clean package -DskipTests
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ap-south-1
      - name: Login ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Dockerfile Lint
        run: |
          docker run --rm \
          -i hadolint/hadolint \
          < user-service/Dockerfile
      - name: Docker Build
        run: |
          docker build \
          -t ${{ secrets.USER_ECR }}:${IMAGE_TAG} \
          ./user-service
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.USER_ECR }}:${{ github.sha }}
          severity: HIGH,CRITICAL
          exit-code: 1
      - name: Push Image
        run: |
          docker push \
          ${{ secrets.USER_ECR }}:${IMAGE_TAG}
